#!/usr/bin/env bash
# (C) 2019 Piotr Biesiada

# needs: ssh-keyscan

# input
hosts="./0hosts.txt" # host;login;password per line

# output
kh=~/.ssh/known_hosts # default

while IFS=";" read -ra host; do
	echo "Adding keys for ${host[0]}"
	ssh-keyscan "${host[0]}" >> "$kh"
	echo "Added keys for ${host[0]}"
done < "$hosts"
