#!/usr/bin/env bash
# (C) 2019 Piotr Biesiada

# needs: sshpass ssh-keyscan

# input
cmds="./0cmds.txt" # commands to issue on all servers
hosts="./0hosts.txt" # host;login;password per line

# output
results="./0results.txt" # program output
kh=~/.ssh/known_hosts # default

while IFS= read -ra l; do
	arr=(${l//;/ })
	host="${arr[0]}"
	user="${arr[1]}"
	pass="${arr[2]}"
	echo "### Running $host... ###" | tee -a "$results"
	sshpass -p"$pass" ssh "$user"@"$host" < "$cmds" >> "$results" 2>> "$results"
	echo "### Done "$host". ###" | tee -a "$results"
done < "$hosts"
