#!/usr/bin/env bash
# (C) 2021 Piotr Biesiada

# needs: ssh sshpass

# input
cmds="./0cmds.txt" # commands to issue on all servers, may need to end by simple exit and enter
hosts="./0hosts.txt" # host;login;password per line

# output
results="./0results.txt" # program output
kh=~/.ssh/known_hosts # default

while IFS= read -ra l; do
	arr=(${l//;/ })
	host="${arr[0]}"
	user="${arr[1]}"
	pass="${arr[2]}"
	echo "### Running $host ###" | tee -a "$results"
	# ssh may need -T or -tt
	sshpass -p"$pass" ssh "$user"@"$host" < "$cmds" >> "$results" 2>> "$results"
	echo "### Done "$host" ###" | tee -a "$results"
done < "$hosts"
